### ISSUE TITLE
infografia-de-gestión-de-proyectos-de-software-JAVIER-NOE

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-javiern-778#2]
[INFOGRAFIA-JAVIER-NOE-CRUZ-ESPAÑA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-javiern-778/files/9420946/INFOGRAFIA-JAVIER-NOE-CRUZ-ESPANA.pdf)

**Comment by ArturoAngonJose** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
